# Generated by Django 5.2.7 on 2025-10-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Optional category image or icon for UI display.', null=True, upload_to='category_icons/'),
        ),
    ]
