# Generated by Django 5.2.7 on 2025-10-15 15:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_orderitem_is_prebook_product_is_prebook_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_prebook_enabled',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prebook_amount',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preorder_deposit_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='is_preorder_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='available_on',
            field=models.DateField(blank=True, help_text='Estimated date product will be shipped.', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False, help_text='Allow purchase even if stock is 0 and requires a deposit.'),
        ),
        migrations.AddField(
            model_name='product',
            name='preorder_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The minimum amount the customer must pay to secure the pre-order.', max_digits=10),
        ),
    ]
